import os
import numpy as np
import random
import torch

from torch.utils.data import ConcatDataset, DataLoader, Subset
from torchvision import datasets, transforms

# Update these paths for your environment
DATA_ROOTS = {
    'StanfordCars': '/path/to/StanfordCars',
    'Flowers':      '/path/to/flowers102',
    'Food':         '/path/to/food',
    'DTD':          '/path/to/dtd',
}

# Synthetic data roots (generated by stable_diffusion_gen.py)
SYN_ROOTS = {
    'StanfordCars': '/path/to/FakeStanfordCars',
    'Flowers':      '/path/to/FakeFlowers',
    'Food':         '/path/to/FakeFood',
    'DTD':          '/path/to/FakeDTD',
}


def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def _syn_dir(dataset, shot, seed):
    root = SYN_ROOTS[dataset]
    suffix = f'{shot}shot' if seed == 0 else f'{shot}shot_seed{seed}'
    return os.path.join(f'{root}{suffix}', 'train')


def _make_transforms(randaug):
    aug = [transforms.RandAugment(num_ops=6)] if randaug else [transforms.RandomHorizontalFlip()]
    train_transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        *aug,
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])
    test_transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])
    return train_transform, test_transform


def _few_shot_indices(targets, shot):
    class_to_indices = {}
    for idx, label in enumerate(targets):
        class_to_indices.setdefault(label, []).append(idx)
    indices = []
    for cls_indices in class_to_indices.values():
        indices.extend(np.random.choice(cls_indices, size=int(shot), replace=False))
    return indices


def _syn_subset(syn_dir, syn_shot, train_transform):
    full = datasets.ImageFolder(syn_dir)
    class_to_indices = {}
    for idx, label in enumerate(full.targets):
        class_to_indices.setdefault(label, []).append(idx)
    indices = []
    for cls_indices in class_to_indices.values():
        indices.extend(np.random.choice(cls_indices, size=int(syn_shot), replace=False))
    ds = datasets.ImageFolder(syn_dir, transform=train_transform)
    return Subset(ds, indices)


def get_dataloaders(dataset, bs, randaug, shot, seed, syn, syn_shot):
    """Returns train_data, test_data, train_loader, test_loader, untransformed_train_data."""
    set_seed(seed)
    if dataset == 'StanfordCars':
        return get_stanford_cars(bs, randaug, shot, seed, syn, syn_shot)
    elif dataset == 'Flowers':
        return get_flowers(bs, randaug, shot, seed, syn, syn_shot)
    elif dataset == 'Food':
        return get_food(bs, randaug, shot, seed, syn, syn_shot)
    elif dataset == 'DTD':
        return get_dtd(bs, randaug, shot, seed, syn, syn_shot)


def get_stanford_cars(batch_size, randaug, shot, seed, syn, syn_shot):
    train_transform, test_transform = _make_transforms(randaug)
    data_path = DATA_ROOTS['StanfordCars']

    if shot is not None:
        full = datasets.ImageFolder(os.path.join(data_path, 'train'))
        indices = _few_shot_indices(full.targets, shot)
        real_ds = Subset(datasets.ImageFolder(os.path.join(data_path, 'train'), transform=train_transform), indices)
        real_ds_no_transform = Subset(full, indices)
    else:
        real_ds = datasets.ImageFolder(os.path.join(data_path, 'train'), transform=train_transform)
        real_ds_no_transform = datasets.ImageFolder(os.path.join(data_path, 'train'))

    if syn:
        syn_ds = _syn_subset(_syn_dir('StanfordCars', shot, seed), syn_shot, train_transform)
        train_dataset = ConcatDataset([real_ds, syn_ds])
        train_dataset_no_transform = None
    else:
        train_dataset = real_ds
        train_dataset_no_transform = real_ds_no_transform

    test_dataset = datasets.ImageFolder(os.path.join(data_path, 'test'), transform=test_transform)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=4, pin_memory=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    return train_dataset, test_dataset, train_loader, test_loader, train_dataset_no_transform


def get_flowers(batch_size, randaug, shot, seed, syn, syn_shot):
    train_transform, test_transform = _make_transforms(randaug)
    data_path = DATA_ROOTS['Flowers']

    if shot is not None:
        indices = []
        for i in range(102):
            chosen = np.random.choice(range(10), size=int(shot), replace=False)
            indices.extend(10 * i + chosen)
        real_ds = Subset(datasets.Flowers102(root=data_path, split='train', transform=train_transform, download=False), indices)
        real_ds_no_transform = Subset(datasets.Flowers102(root=data_path, split='train', download=False), indices)
    else:
        real_ds = datasets.Flowers102(root=data_path, split='train', transform=train_transform, download=False)
        real_ds_no_transform = datasets.Flowers102(root=data_path, split='train', download=False)

    if syn:
        syn_ds = _syn_subset(_syn_dir('Flowers', shot, seed), syn_shot, train_transform)
        train_dataset = ConcatDataset([real_ds, syn_ds])
        train_dataset_no_transform = None
    else:
        train_dataset = real_ds
        train_dataset_no_transform = real_ds_no_transform

    test_dataset = datasets.Flowers102(root=data_path, split='test', transform=test_transform, download=False)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=4, pin_memory=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    return train_dataset, test_dataset, train_loader, test_loader, train_dataset_no_transform


def get_food(batch_size, randaug, shot, seed, syn, syn_shot):
    train_transform, test_transform = _make_transforms(randaug)
    data_path = DATA_ROOTS['Food']

    full = datasets.Food101(root=data_path, split='train', download=True)
    if shot is not None:
        indices = _few_shot_indices(full._labels, shot)
        real_ds = Subset(datasets.Food101(root=data_path, split='train', transform=train_transform, download=True), indices)
        real_ds_no_transform = Subset(full, indices)
    else:
        real_ds = datasets.Food101(root=data_path, split='train', transform=train_transform, download=True)
        real_ds_no_transform = full

    if syn:
        syn_ds = _syn_subset(_syn_dir('Food', shot, seed), syn_shot, train_transform)
        train_dataset = ConcatDataset([real_ds, syn_ds])
        train_dataset_no_transform = None
    else:
        train_dataset = real_ds
        train_dataset_no_transform = real_ds_no_transform

    test_dataset = datasets.Food101(root=data_path, split='test', transform=test_transform, download=False)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=4, pin_memory=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    return train_dataset, test_dataset, train_loader, test_loader, train_dataset_no_transform


def get_dtd(batch_size, randaug, shot, seed, syn, syn_shot):
    train_transform, test_transform = _make_transforms(randaug)
    data_path = DATA_ROOTS['DTD']

    full = datasets.DTD(root=data_path, split='train', download=True)
    if shot is not None:
        indices = _few_shot_indices(full._labels, shot)
        real_ds = Subset(datasets.DTD(root=data_path, split='train', transform=train_transform, download=True), indices)
        real_ds_no_transform = Subset(full, indices)
    else:
        real_ds = datasets.DTD(root=data_path, split='train', transform=train_transform, download=True)
        real_ds_no_transform = full

    if syn:
        syn_ds = _syn_subset(_syn_dir('DTD', shot, seed), syn_shot, train_transform)
        train_dataset = ConcatDataset([real_ds, syn_ds])
        train_dataset_no_transform = None
    else:
        train_dataset = real_ds
        train_dataset_no_transform = real_ds_no_transform

    test_dataset = datasets.DTD(root=data_path, split='test', transform=test_transform, download=True)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=4, pin_memory=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    return train_dataset, test_dataset, train_loader, test_loader, train_dataset_no_transform

